//! Tables read out of ceplang_en.dll 6.2 by the scripts in _fe/. Regenerate
//! rather than edit: `python state_table.py --rust`, `python abbrev_table.py --rust`,
//! `python peek_vals.py list 0xb58050 --rust ACRONYMS`.

/// ceplang_en.dll `us_states` @0xb565a0, 124 records.
pub const STATES: &[(&str, bool, &[&str])] = &[
    ("AL",    true,  &["alabama"]),
    ("Al",    true,  &["alabama"]),
    ("Ala",   false, &["alabama"]),
    ("AK",    false, &["alaska"]),
    ("Ak",    false, &["alaska"]),
    ("AS",    true,  &["arkansas"]),
    ("AS",    true,  &["american", "samoa"]),
    ("AZ",    false, &["arizona"]),
    ("Az",    false, &["arizona"]),
    ("CA",    false, &["california"]),
    ("Ca",    false, &["california"]),
    ("Cal",   true,  &["california"]),
    ("Calif", false, &["california"]),
    ("CO",    true,  &["colorado"]),
    ("Co",    true,  &["colorado"]),
    ("Colo",  false, &["colorado"]),
    ("CT",    true,  &["connecticut"]),
    ("DC",    false, &["d", "c"]),
    ("DE",    false, &["delaware"]),
    ("De",    true,  &["delaware"]),
    ("Del",   true,  &["delaware"]),
    ("FL",    false, &["florida"]),
    ("Fl",    true,  &["florida"]),
    ("Fla",   false, &["florida"]),
    ("GA",    false, &["georgia"]),
    ("Ga",    false, &["georgia"]),
    ("GA",    false, &["guam"]),
    ("HI",    true,  &["hawaii"]),
    ("Hi",    true,  &["hawaii"]),
    ("IA",    false, &["iowa"]),
    ("Ia",    true,  &["iowa"]),
    ("ID",    true,  &["idaho"]),
    ("IL",    true,  &["illinois"]),
    ("Il",    true,  &["illinois"]),
    ("ILL",   true,  &["illinois"]),
    ("IN",    true,  &["indiana"]),
    ("Ind",   true,  &["indiana"]),
    ("KS",    false, &["kansas"]),
    ("Ks",    false, &["kansas"]),
    ("Kans",  false, &["kansas"]),
    ("KY",    true,  &["kentucky"]),
    ("Ky",    true,  &["kentucky"]),
    ("LA",    true,  &["louisiana"]),
    ("La",    true,  &["louisiana"]),
    ("Lou",   true,  &["louisiana"]),
    ("Lous",  true,  &["louisiana"]),
    ("MA",    true,  &["massachusetts"]),
    ("Mass",  true,  &["massachusetts"]),
    ("Ma",    true,  &["massachusetts"]),
    ("MD",    true,  &["maryland"]),
    ("Md",    true,  &["maryland"]),
    ("ME",    true,  &["maine"]),
    ("Me",    true,  &["maine"]),
    ("MH",    false, &["marshall", "islands"]),
    ("MI",    false, &["michigan"]),
    ("Mi",    true,  &["michigan"]),
    ("Mich",  true,  &["michigan"]),
    ("MN",    true,  &["minnesota"]),
    ("Minn",  true,  &["minnesota"]),
    ("MS",    true,  &["mississippi"]),
    ("Miss",  true,  &["mississippi"]),
    ("MT",    true,  &["montana"]),
    ("Mt",    true,  &["montana"]),
    ("MO",    true,  &["missouri"]),
    ("Mo",    true,  &["missouri"]),
    ("NC",    true,  &["north", "carolina"]),
    ("ND",    true,  &["north", "dakota"]),
    ("NE",    true,  &["nebraska"]),
    ("Ne",    true,  &["nebraska"]),
    ("Neb",   true,  &["nebraska"]),
    ("NH",    true,  &["new", "hampshire"]),
    ("NJ",    false, &["new", "jersey"]),
    ("NM",    false, &["new", "mexico"]),
    ("NV",    false, &["nevada"]),
    ("Nev",   false, &["nevada"]),
    ("NY",    false, &["new", "york"]),
    ("OH",    true,  &["ohio"]),
    ("OK",    true,  &["oklahoma"]),
    ("Okla",  false, &["oklahoma"]),
    ("OR",    true,  &["oregon"]),
    ("Or",    true,  &["oregon"]),
    ("Ore",   true,  &["oregon"]),
    ("PA",    true,  &["pennsylvania"]),
    ("Pa",    true,  &["pennsylvania"]),
    ("Penn",  true,  &["pennsylvania"]),
    ("PR",    true,  &["puerto", "rico"]),
    ("PW",    false, &["palau"]),
    ("RI",    true,  &["rhode", "island"]),
    ("SC",    true,  &["south", "carolina"]),
    ("SD",    true,  &["south", "dakota"]),
    ("TN",    true,  &["tennessee"]),
    ("Tn",    true,  &["tennessee"]),
    ("Tenn",  true,  &["tennessee"]),
    ("TX",    true,  &["texas"]),
    ("Tx",    true,  &["texas"]),
    ("Tex",   true,  &["texas"]),
    ("UT",    true,  &["utah"]),
    ("VA",    true,  &["virginia"]),
    ("VI",    true,  &["virgin", "islands"]),
    ("WA",    true,  &["washington"]),
    ("Wa",    true,  &["washington"]),
    ("Wash",  true,  &["washington"]),
    ("WI",    true,  &["wisconsin"]),
    ("Wi",    true,  &["wisconsin"]),
    ("WV",    true,  &["west", "virginia"]),
    ("WY",    true,  &["wyoming"]),
    ("Wy",    true,  &["wyoming"]),
    ("Wyo",   false, &["wyoming"]),
    ("AB",    true,  &["alberta"]),
    ("Alta",  false, &["alberta"]),
    ("MB",    true,  &["manitoba"]),
    ("NB",    true,  &["new", "brunswick"]),
    ("NL",    true,  &["newfoundland"]),
    ("NS",    true,  &["nova", "scotia"]),
    ("NU",    true,  &["nunavut"]),
    ("ON",    true,  &["ontario"]),
    ("Ont",   false, &["ontario"]),
    ("PE",    true,  &["prince-edward", "island"]),
    ("PEI",   true,  &["prince-edward", "island"]),
    ("QC",    true,  &["quebec"]),
    ("Que",   true,  &["quebec"]),
    ("Sask",  false, &["saskatchewan"]),
    ("SK",    false, &["saskatchewan"]),
    ("YT",    false, &["yukon", "territory"]),
];

/// ceplang_en.dll abbreviation table @0xaf990, 52 entries, tried before
/// any other rule. See `abbreviation`.
pub const ABBREVIATIONS: &[(&str, &str)] = &[
    ("Adm.", "admiral"),
    ("R.Adm.", "rear admiral"),
    ("V.Adm.", "vice admiral"),
    ("Adml.", "admiral"),
    ("Amn.", "airman"),
    ("B.Gen.", "brigadier general"),
    ("Brig.", "brigadier"),
    ("Capt.", "captain"),
    ("Cdr.", "commander"),
    ("Cmd.", "commander"),
    ("Cmdr.", "commander"),
    ("Col.", "colonel"),
    ("Cpl.", "corporal"),
    ("Cpt.", "captain"),
    ("Ens.", "ensign"),
    ("Gen.", "general"),
    ("LCpl", "lance corporal"),
    ("Lieut.", "lieutenant"),
    ("Maj.", "major"),
    ("Pfc.", "private first class"),
    ("Pvt.", "private"),
    ("Sfc", "sergeant first class"),
    ("Sgt", "sergeant"),
    ("Sgt.", "sergeant"),
    ("Spc.", "specialist"),
    ("Sp3c.", "specialist third class"),
    ("Pres.", "president"),
    ("Sen.", "senator"),
    ("Rep.", "representative"),
    ("Msgr.", "monsignor"),
    ("Rev.", "reverend"),
    ("Prof.", "professor"),
    ("Chas.", "charles"),
    ("Danl.", "daniel"),
    ("Danl", "daniel"),
    ("Edw.", "edward"),
    ("Fredk.", "frederick"),
    ("Fredk", "frederick"),
    ("Geo.", "george"),
    ("Jas.", "james"),
    ("Jos.", "joseph"),
    ("Robt.", "robert"),
    ("Saml.", "samuel"),
    ("Thos.", "thomas"),
    ("Wm.", "william"),
    ("Hon.", "honorable"),
    ("Esq.", "esquire"),
    ("Sr.", "senior"),
    ("Ltd.", "limited"),
    ("Intl", "international"),
    ("Co.", "company"),
    ("Xmas", "christmas"),
];

/// ceplang_en.dll @0xb58050, 103 entries.
pub const ACRONYMS: &[&str] = &[
    "US", "USD", "usd", "ESD", "esd", "UN", "AARP", "aarp",
    "UAE", "uae", "BA", "MS", "MIT", "mit", "SRI", "SRO",
    "ID", "UV", "uv", "AIG", "TES", "ucla", "PO", "UCLA",
    "EDU", "edu", "HMM", "UPS", "IAEA", "iaea", "FIS", "fis",
    "UPI", "upi", "IT", "AM", "OS", "os", "AMA", "GED",
    "ICU", "UNC", "unc", "UCLA", "ucla", "USC", "usc", "FAO",
    "APY", "apy", "ASPCA", "aspca", "COD", "SOS", "sos", "OAS",
    "oas", "ECU", "ecu", "ywha", "YHWA", "UID", "WHO", "MIA",
    "IQ", "ALS", "DUI", "dui", "DOA", "doa", "DWI", "dwi",
    "ESP", "FYI", "fyi", "OEM", "oem", "RIP", "USAF", "usaf",
    "USN", "usn", "USNR", "usnr", "USMC", "usmc", "CPO", "cpo",
    "GIS", "gis", "CES", "MBA", "mba", "GPA", "gpa", "NCO",
    "nco", "ABD", "abd", "EST", "BEA", "FAQ", "faq",
];
